version: '3.8'
services:
  backend:
    build:
      context: ./
    container_name: backend
    ports:
      - "8080:8080"
    networks:
      - app-network
    volumes:
      - /Users/hal9000/Projects/SWE573-Fall24/env.properties:/env.properties
    environment:
        SPRING_CONFIG_LOCATION: file:env.properties

  frontend:
    build:
      context: ./whatsthis-frontend
    container_name: frontend
    ports:
      - "3000:3000"
    networks:
      - app-network
    environment:
      - NEXT_PUBLIC_API_URL=http://34.56.184.233:8080/api

  db:
    image: postgres:latest
    container_name: database
    environment:
      POSTGRES_DB: whatsthis
      POSTGRES_USER: hal9000
      POSTGRES_PASSWORD: 4444
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
